import { Job } from "../../../../../../packages/shared-types/src/models/job";

export const JOBS_DATA: Job[] = [
  {
    id: "1",
    title: "Backend Developer Node.js",
    department: "Engineering",
    location: "remote",
    city: "Buenos Aires",
    description: "Sumate para escalar microservicios y optimizar bases de datos en MongoDB. Valoramos conocimientos en arquitecturas limpias.",
    requirements: ["Node.js", "Express", "MongoDB", "TypeScript"],
    niceToHave: ["Docker", "AWS"],
    salaryMin: 2500,
    salaryMax: 4000,
    currency: "USD",
    status: "open",
    hiringManagerId: "mgr-01",
    responsabilities: [
      "Diseñar y mantener APIs REST escalables",
      "Optimizar consultas y modelado de datos",
      "Revisar código y mentorizar a desarrolladores junior",
    ],
    benefits: ["Work from home", "Capacitación anual", "Seguro médico"],
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-05-12"),
    publishedAt: new Date("2026-05-12"),
  },
  {
    id: "2",
    title: "UX/UI Designer",
    department: "Product",
    location: "remote",
    city: "Buenos Aires",
    description: "Diseñá interfaces modernas y funcionales. Trabajo codo a codo con el equipo de front para asegurar la fidelidad de los mockups de Figma.",
    requirements: ["Figma", "Adobe XD", "Design Systems"],
    niceToHave: ["Framer", "Prototyping"],
    salaryMin: 2000,
    salaryMax: 3500,
    currency: "USD",
    status: "open",
    hiringManagerId: "mgr-02",
    responsabilities: [
      "Crear prototipos de alta fidelidad",
      "Colaborar con product managers y desarrolladores",
      "Implementar mejoras basadas en feedback de usuarios",
    ],
    benefits: ["Trabajo remoto 100%", "20 días de vacaciones", "Presupuesto para capacitación"],
    createdAt: new Date("2026-05-02"),
    updatedAt: new Date("2026-05-11"),
    publishedAt: new Date("2026-05-11"),
  },
  {
    id: "3",
    title: "Fullstack Developer (React/Python)",
    department: "Engineering",
    location: "hybrid",
    city: "Córdoba",
    description: "Buscamos un perfil versátil que pueda manejar el frontend en React y servicios de inteligencia artificial en Python.",
    requirements: ["React", "Python", "FastAPI"],
    niceToHave: ["GraphQL", "Machine Learning"],
    salaryMin: 3000,
    salaryMax: 5000,
    currency: "USD",
    status: "open",
    hiringManagerId: "mgr-01",
    responsabilities: [
      "Construir interfaces interactivas en React",
      "Diseñar servicios backend eficientes en Python",
      "Desplegar aplicaciones y monitorear su performance",
    ],
    benefits: ["Horario flexible", "Sueldo competitivo", "Espacio de oficina moderno"],
    createdAt: new Date("2026-05-03"),
    updatedAt: new Date("2026-05-10"),
    publishedAt: new Date("2026-05-10"),
  },
  {
    id: "4",
    title: "QA Automation Engineer",
    department: "Engineering",
    location: "on-site",
    city: "Rosario",
    description: "Responsable de asegurar la calidad mediante tests automatizados (Cypress/Playwright). Implementación de CI/CD.",
    requirements: ["Cypress", "JavaScript", "Selenium"],
    niceToHave: ["Playwright", "Jenkins"],
    salaryMin: 2400,
    salaryMax: 3600,
    currency: "USD",
    status: "open",
    hiringManagerId: "mgr-03",
    responsabilities: [
      "Diseñar y ejecutar suites de tests automatizados",
      "Integrar pruebas en pipelines de CI/CD",
      "Reportar y validar fallos con el equipo de desarrollo",
    ],
    benefits: ["Seguro médico", "Clases de inglés", "Snacks en oficina"],
    createdAt: new Date("2026-05-04"),
    updatedAt: new Date("2026-05-09"),
    publishedAt: new Date("2026-05-09"),
  },
  {
    id: "5",
    title: "Data Analyst",
    department: "Data Science",
    location: "remote",
    city: "Buenos Aires",
    description: "Análisis de grandes volúmenes de datos para la toma de decisiones estratégicas. Experiencia en SQL y visualización de datos.",
    requirements: ["SQL", "Python", "PowerBI", "Tableau"],
    niceToHave: ["R", "BigQuery"],
    salaryMin: 2200,
    salaryMax: 3800,
    currency: "USD",
    status: "paused",
    hiringManagerId: "mgr-02",
    responsabilities: [
      "Analizar información para detectar tendencias",
      "Diseñar dashboards de negocio",
      "Presentar insights a stakeholders",
    ],
    benefits: ["Home office", "Bonificación por desempeño", "Clases de datos"],
    createdAt: new Date("2026-05-05"),
    updatedAt: new Date("2026-05-08"),
    publishedAt: new Date("2026-05-08"),
  },
];
