import { Job } from '@ats/shared-types';

export const JOBS_DATA: Job[] = [
  {
    id: '1',
    slug: 'senior-frontend-developer',
    title: 'Senior Frontend Developer',
    department: 'Tecnología',
    seniority: 'senior',
    location: 'remote',
    city: 'Buenos Aires',
    type: 'Full-time',
    candidates: 24,
    description:
      'Sumate para escalar microservicios y optimizar bases de datos en MongoDB. Valoramos conocimientos en arquitecturas limpias.',
    skills: [
      { name: 'Node.js', yearsOfExperience: 5, weight: 5, type: 'mandatory' },
      { name: 'Express', yearsOfExperience: 3, weight: 4, type: 'mandatory' },
      { name: 'MongoDB', yearsOfExperience: 3, weight: 5, type: 'mandatory' },
      { name: 'TypeScript', yearsOfExperience: 4, weight: 4, type: 'mandatory' },
      { name: 'Docker', yearsOfExperience: 1, weight: 3, type: 'desirable' },
      { name: 'AWS', yearsOfExperience: 1, weight: 2, type: 'desirable' },
    ],
    salaryMin: 2500,
    salaryMax: 4000,
    currency: 'USD',
    status: 'open',
    hiringManagerId: 'mgr-01',
    observations:
      'Se valorará portfolio con proyectos open source. Entrevista técnica incluye pair programming.',
    additionalCriteria: [
      'Disponibilidad para trabajar en horario flexible.',
      'Se requiere inglés técnico intermedio para lectura de documentación.',
    ],
    responsabilities: [
      'Desarrollar y mantener componentes frontend de alta calidad',
      'Colaborar con el equipo de diseño para implementar interfaces intuitivas',
      'Optimizar aplicaciones para máximo rendimiento y escalabilidad',
      'Participar en revisiones de código y mentoría de desarrolladores junior',
      'Contribuir a la arquitectura técnica del producto',
    ],
    benefits: [
      'Trabajo remoto u híbrido',
      'Seguro médico premium',
      '20 días de vacaciones + feriados',
      'Presupuesto para capacitación y conferencias',
      'Equipamiento de última generación',
    ],
    createdAt: new Date('2026-05-01'),
    updatedAt: new Date('2026-05-12'),
    publishedAt: new Date('2026-05-12'),
  },
  {
    id: '2',
    slug: 'ux-ui-designer',
    title: 'UX/UI Designer',
    department: 'Diseño',
    seniority: 'semi-senior',
    location: 'remote',
    city: 'Buenos Aires',
    type: 'Full-time',
    candidates: 18,
    description:
      'Diseñá interfaces modernas y funcionales. Trabajo codo a codo con el equipo de front para asegurar la fidelidad de los mockups de Figma.',
    skills: [
      { name: 'Figma', yearsOfExperience: 3, weight: 5, type: 'mandatory' },
      { name: 'Adobe XD', yearsOfExperience: 2, weight: 4, type: 'mandatory' },
      { name: 'Design Systems', yearsOfExperience: 2, weight: 4, type: 'mandatory' },
      { name: 'Framer', yearsOfExperience: 1, weight: 2, type: 'desirable' },
      { name: 'Prototyping', yearsOfExperience: 2, weight: 3, type: 'desirable' },
    ],
    salaryMin: 2000,
    salaryMax: 3500,
    currency: 'USD',
    status: 'open',
    hiringManagerId: 'mgr-02',
    responsabilities: [
      'Crear prototipos de alta fidelidad',
      'Colaborar con product managers y desarrolladores',
      'Implementar mejoras basadas en feedback de usuarios',
    ],
    benefits: [
      'Trabajo remoto 100%',
      '20 días de vacaciones',
      'Presupuesto para capacitación',
    ],
    createdAt: new Date('2026-05-02'),
    updatedAt: new Date('2026-05-11'),
    publishedAt: new Date('2026-05-11'),
  },
  {
    id: '3',
    slug: 'fullstack-developer-react-python',
    title: 'Fullstack Developer (React/Python)',
    department: 'Tecnología',
    seniority: 'senior',
    location: 'hybrid',
    city: 'Córdoba',
    type: 'Full-time',
    candidates: 31,
    description:
      'Buscamos un perfil versátil que pueda manejar el frontend en React y servicios de inteligencia artificial en Python.',
    skills: [
      { name: 'React', yearsOfExperience: 4, weight: 5, type: 'mandatory' },
      { name: 'Python', yearsOfExperience: 4, weight: 5, type: 'mandatory' },
      { name: 'FastAPI', yearsOfExperience: 2, weight: 4, type: 'mandatory' },
      { name: 'GraphQL', yearsOfExperience: 1, weight: 3, type: 'desirable' },
      { name: 'Machine Learning', yearsOfExperience: 1, weight: 2, type: 'desirable' },
    ],
    salaryMin: 3000,
    salaryMax: 5000,
    currency: 'USD',
    status: 'open',
    hiringManagerId: 'mgr-01',
    responsabilities: [
      'Construir interfaces interactivas en React',
      'Diseñar servicios backend eficientes en Python',
      'Desplegar aplicaciones y monitorear su performance',
    ],
    benefits: [
      'Horario flexible',
      'Sueldo competitivo',
      'Espacio de oficina moderno',
    ],
    createdAt: new Date('2026-05-03'),
    updatedAt: new Date('2026-05-10'),
    publishedAt: new Date('2026-05-10'),
  },
  {
    id: '4',
    slug: 'qa-automation-engineer',
    title: 'QA Automation Engineer',
    department: 'Tecnología',
    seniority: 'semi-senior',
    location: 'on-site',
    city: 'Rosario',
    type: 'Full-time',
    candidates: 15,
    description:
      'Responsable de asegurar la calidad mediante tests automatizados (Cypress/Playwright). Implementación de CI/CD.',
    skills: [
      { name: 'Cypress', yearsOfExperience: 3, weight: 5, type: 'mandatory' },
      { name: 'JavaScript', yearsOfExperience: 3, weight: 4, type: 'mandatory' },
      { name: 'Selenium', yearsOfExperience: 2, weight: 4, type: 'mandatory' },
      { name: 'Playwright', yearsOfExperience: 2, weight: 4, type: 'desirable' },
      { name: 'Jenkins', yearsOfExperience: 1, weight: 3, type: 'desirable' },
    ],
    salaryMin: 2400,
    salaryMax: 3600,
    currency: 'USD',
    status: 'open',
    hiringManagerId: 'mgr-03',
    responsabilities: [
      'Diseñar y ejecutar suites de tests automatizados',
      'Integrar pruebas en pipelines de CI/CD',
      'Reportar y validar fallos con el equipo de desarrollo',
    ],
    benefits: ['Seguro médico', 'Clases de inglés', 'Snacks en oficina'],
    createdAt: new Date('2026-05-04'),
    updatedAt: new Date('2026-05-09'),
    publishedAt: new Date('2026-05-09'),
  },
  {
    id: '5',
    slug: 'data-analyst',
    title: 'Data Analyst',
    department: 'Data',
    seniority: 'mid-level',
    location: 'remote',
    city: 'Buenos Aires',
    type: 'Full-time',
    candidates: 22,
    description:
      'Análisis de grandes volúmenes de datos para la toma de decisiones estratégicas. Experiencia en SQL y visualización de datos.',
    skills: [
      { name: 'SQL', yearsOfExperience: 4, weight: 5, type: 'mandatory' },
      { name: 'Python', yearsOfExperience: 3, weight: 4, type: 'mandatory' },
      { name: 'PowerBI', yearsOfExperience: 2, weight: 4, type: 'mandatory' },
      { name: 'Tableau', yearsOfExperience: 2, weight: 4, type: 'mandatory' },
      { name: 'R', yearsOfExperience: 1, weight: 2, type: 'desirable' },
      { name: 'BigQuery', yearsOfExperience: 1, weight: 3, type: 'desirable' },
    ],
    salaryMin: 2200,
    salaryMax: 3800,
    currency: 'USD',
    status: 'paused',
    hiringManagerId: 'mgr-02',
    responsabilities: [
      'Analizar información para detectar tendencias',
      'Diseñar dashboards de negocio',
      'Presentar insights a stakeholders',
    ],
    benefits: ['Home office', 'Bonificación por desempeño', 'Clases de datos'],
    createdAt: new Date('2026-05-05'),
    updatedAt: new Date('2026-05-08'),
    publishedAt: new Date('2026-05-08'),
  },
];

export function getJobBySlug(slug: string) {
  const normalizedSlug = slug?.toString().trim().toLowerCase();
  return JOBS_DATA.find((job) => job.slug?.toLowerCase() === normalizedSlug);
}
